modLoader="javafml"
loaderVersion="[43,)"
license="AGPL-3.0"

[[mods]]
    modId="oredustry"
    version="0.4.0"

    displayName="Oredustry"
    authors="NewJumper"
    logoFile="logo.png"
#    credits="credits woooo"

    description='''A mod that can multiply ores!'''

[[dependencies.oredustry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    side="BOTH"

[[dependencies.oredustry]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    side="BOTH"
