modLoader="javafml"
loaderVersion="[43,44)"
license="AGPL-3.0"

[[mods]]
    modId="oredustry"
    version="0.5.0"

    displayName="Oredustry"
    authors="NewJumper"
    logoFile="banner.png"
#    credits="credits woooo"

    description='''A mod that can multiply ores!'''

[[dependencies.oredustry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.19.3)"
    side="BOTH"

[[dependencies.oredustry]]
    modId="forge"
    mandatory=true
    versionRange="[43,44)"
    side="BOTH"
